# Generated by Django 5.2.8 on 2025-12-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_reportes/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='app_reportes.usuario'),
        ),
    ]
