# Generated by Django 5.2.8 on 2025-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0003_remove_reporte_ubicacion_reporte_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
