# Generated by Django 5.2.8 on 2025-12-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reportes', '0004_alter_reporte_latitud_alter_reporte_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=50),
        ),
    ]
